### ISSUE TITLE
yarn build失败

### ISSUE THREAD

**Issue by Yofo-me** [CareyWang/sub-web#120]
root@hk-allin:/tmp/sub-web# yarn build
yarn run v1.22.19
$ vue-cli-service build

⠦  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/sub-web/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/sub-web/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/sub-web/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/sub-web/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/sub-web/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/sub-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/sub-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠋  Building for production.../tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/sub-web/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/sub-web/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/sub-web/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/sub-web/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/sub-web/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/sub-web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/sub-web/node_modules/cache-loader/dist/index.js:147:7
    at /tmp/sub-web/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Leoin1** [comment]
运行下这个
`export NODE_OPTIONS=--openssl-legacy-provider`
之后在build

**Comment by 281677160** [comment]
应该是Node.js v18.10.0版本太高了，用指定的 Node.js v16版本试试
