### ISSUE TITLE
大佬，运行docker-compose up -d显示这个

### ISSUE THREAD

**Issue by victoryLV** [CareyWang/sub-web#42]
[root@VM-4-5-centos sub-web]# docker-compose up -d
Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?

Supported filenames: docker-compose.yml, docker-compose.yaml, fig.yml, fig.yaml
[root@VM-4-5-centos sub-web]#

**Comment by CareyWang** [comment]
@victoryLV cd sub-web-services

**Comment by victoryLV** [comment]
大佬，进入目录又显示这个
root@VM-4-5-centos sub-web-services]# docker-compose up -d
Please be aware that .yml is the expected extension in most cases, and using .yaml can cause compatibility issues in future.

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 64, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 83, in get_project
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 68, in load
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 466, in load_yaml
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml", line 93, in safe_load
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml", line 71, in load
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.constructor", line 37, in get_single_data
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 36, in get_single_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 55, in compose_document
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 84, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 133, in compose_mapping_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 84, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 133, in compose_mapping_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 84, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 133, in compose_mapping_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 82, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 110, in compose_sequence_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.parser", line 98, in check_event
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.parser", line 486, in parse_flow_sequence_entry
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 116, in check_token
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 252, in fetch_more_tokens
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 680, in fetch_plain
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 1309, in scan_plain
yaml.scanner.ScannerError: while scanning a plain scalar
  in "./docker-compose.yaml", line 18, column 73
found unexpected ':'
  in "./docker-compose.yaml", line 18, column 85
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
[root@VM-4-5-centos sub-web-services]#
