### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by CnSuperYoung** [CareyWang/sub-web#62]
`
[root@HK-Server-1 sub-web]# yarn serve
yarn run v1.22.10
$ vue-cli-service serve
/root/sub-web/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                                                      ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/sub-web/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`

**Comment by CareyWang** [comment]
@CnSuperYoung 提供下 node 版本。建议使用 10.x 12.x

**Comment by Comah** [comment]
我的也是這樣
