### ISSUE TITLE
docker build出现错误

### ISSUE THREAD

**Issue by haohaoget** [CareyWang/sub-web#70]
root@VM-0-10-ubuntu:~/sub-web# docker build -t xxxx/subweb:v1 .
Sending build context to Docker daemon    164MB
Step 1/12 : FROM node:12-alpine AS dependencies
 ---> dc1848067319
Step 2/12 : WORKDIR /app
 ---> Using cache
 ---> 6d5b6b562a0e
Step 3/12 : COPY package.json ./
 ---> Using cache
 ---> af3339b53f51
Step 4/12 : RUN yarn install
 ---> Using cache
 ---> 2b0038ce70a5
Step 5/12 : FROM dependencies AS build
 ---> 2b0038ce70a5
Step 6/12 : WORKDIR /app
 ---> Using cache
 ---> 741b570d03b0
Step 7/12 : COPY . /app
 ---> Using cache
 ---> 5de02a32fbe4
Step 8/12 : RUN yarn build
 ---> Running in cd9218ee1e69
yarn run v1.22.5
$ vue-cli-service build

-  Building for production...
 ERROR  TypeError: ext[key].bind is not a function
TypeError: ext[key].bind is not a function
    at /app/node_modules/css-select/node_modules/domutils/index.js:12:28
    at Array.forEach (<anonymous>)
    at /app/node_modules/css-select/node_modules/domutils/index.js:11:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/app/node_modules/css-select/node_modules/domutils/index.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/css-select/lib/pseudos.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
root@VM-0-10-ubuntu:~/sub-web# node -v
v10.19.0
root@VM-0-10-ubuntu:~/sub-web# yarn -v
1.22.11

**Comment by chauncey09** [comment]
我这里也是报错，但是错误不一样：
[root@localhost sub-web]# docker build -t subweb:v1 ./
Sending build context to Docker daemon   618 kB
Step 1/15 : FROM node:12-alpine AS dependencies
Error parsing reference: "node:12-alpine AS dependencies" is not a valid repository/tag: invalid reference format

**Comment by chauncey09** [comment]
同样报错：
Step 8/12 : RUN yarn build
 ---> Running in b7609f2e1a5a
yarn run v1.22.5
$ vue-cli-service build

-  Building for production...
 ERROR  Failed to compile with 1 error3:47:18 PM

Syntax Error: Error: No ESLint configuration found.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1

**Comment by jiangmw** [comment]
同样报错

**Comment by CareyWang** [comment]
建议先升级docker版本至最新，再重试。
全新安装docker: `bash <(curl -fsSL https://get.docker.com)`
